---
title: "Data Wrangling Instructions"
author: "Prepared by Joey Hulbert, Washington State University"
date: July, 2022 (in progress)
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = "/Users/redcedar/ServerFiles/redcedar/") 
```


# Data Wrangle Approach

The overall approach is to model empirical data collected by community scientists with ancillary environmental data (climate, topographic, and soils) to identify important predictors of western redcedar dieback.

  * [Data Wrangle Instructions](./data-wrangle/Data-Wrangle-v1.html)
    + iNat Data
    + Environmental Data
      + [Climate Data](./data-wrangle/climate/Climate-Data-Extraction.html)
      + [Topography Data](./data-wrangle/topo/Topo-Data-Extraction---ArcGIS.html)
      + [Soils Data](./data-wrangle/soils/Soil-Data-Extraction.html)

# Datasets

## iNat Data - Empirical Tree Points

Data were downloaded from the [Wester Redcedar Dieback Map](https://www.inaturalist.org/projects/western-redcedar-dieback-map) project after 1500 observations were shared. 

These data were then subset to include only gps information to use in collecting ancillary data.

## Ancillary Climate Data

Data were downloaded for the iNat GPS locations using the ClimateNA Tool. Instructions are available in the [Climate Data Wrangle](./data-wrangle/climate/Climate-Data-Extraction.html) file.

There were many time series (different intervals where data were averaged) of the downscaled climate variables available. 

* Grouping explored
  + data averaged over 30 year normals (1991-2020)
    + Monthly
    + Seasonal
    + Annual
  + data averaged over last decade (2011-2020)
    + Monthly
    + Seasonal
    + Annual

## Ancillary Topography Data

Ancillary Topographic data were calculated and extracted for iNat GPS points in ArcGIS. The methods are described in the [Topography Data Wrangle](./data-wrangle/topo/Topo-Data-Extraction---ArcGIS.html) file.


## Ancillary Soils Data

gSURRGO data were downloaded for states containing iNAT observations. Instructions for extracting the soils data using Arc GIS Pro are included  in the [Soils Data Wrangle](./data-wrangle/soils/Soil-Data-Extraction.html) file.

