---
title: "Soil Data Extraction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sidenote

Place holder to remind me to read this paper that uses soil data: https://www.sciencedirect.com/science/article/pii/S0378112718315159?casa_token=yB8_4j_LcCMAAAAA:MwWJnLJyW5vVMMvYHK86H2EMpwIN6zqhxydcB_XsRgPxljYtJgHvbTrLMAbLVdaC9UxDki1w

## Purpose

The purpose of this Markdown Document is to record the methods for extracting soils data for the redcedar GPS points.

Unfortunately, I had to do this with windows because the soils data I am first exploring are provided in arcmap database formats (.gdb). 

## Additional Considerations

* Possible options to move forward include: 
  + Maybe I could actually convert them in ArcMap to another format? 
  + **Extracting data from rasters for gps points and exporting into .csv format using arcGIS for analyses in OSX.**
  + Look for alternative soils data that are in another format?
  
Below are the methods I used to extract the soils data for the GPS points.

## Soil Data

Review the [gSSURGO User Guide (PDF)](https://www.nrcs.usda.gov/wps/portal/nrcs/detail/soils/survey/geo/?cid=nrcs142p2_053631) for data descriptions and instructions. 

* Associated Tables in the gSSURGO Database
  + "A complete description of the tables and their relationships is included on the [SSURGO webpage](http://www.nrcs.usda.gov/wps/portal/nrcs/detail/soils/survey/geo/?cid=nrcs142p2_053631). Some
of the commonly used tables are described below. Specific information is located in the SSURGO Tables
and Columns Report document found on the [SSURGO Structural Metadata and Documentation
webpage](https://www.nrcs.usda.gov/wps/portal/nrcs/detail/soils/survey/geo/?cid=nrcs142p2_053631)."


## Download Data

  * Download gSSURGO data from the [USDA Geospatial Data Gateway](https://gdg.sc.egov.usda.gov/GDGHome_DirectDownLoad.aspx)
    + click on the link to 'Soils' - Redirects you to a the [NRCS Box Folder](https://nrcs.app.box.com/v/soils)
    + I downloaded OR and WA data from the folder 'October 2021 gSSURGO by State'.
<<<<<<< HEAD
      + Note the zip files for each state was ~500MB


Working with gSSURGO data is kind of awkward because you have to join tables of interest to the base raster file before you can map those table variables.
=======
    + Working with gSSURGO data is kind of awkward because you have to join tables of interest to the base raster file before you can map those table variables.
>>>>>>> 5f4526c2e8e642bb0d006fdfc0247a36efa9c7de
  
  
### Warning

Note, if you have trouble with having enough memory, check that gps points were subset per state first. 
  
## Wrangle Shapefiles in ArcGIS Pro  

### Add Data Layers

  * Add Data
      + Add MapunitRaster_10m for each state, rename content based on state
        + In the Map Tab of ArcGIS Pro, click 'add data', browse to downloaded folder (geodatabase - .gbd), find raster file in list
          + Note I had trouble finding it in windows explorer on the second attempt to complete these instructions
        + Add CSV with iNat GPS - Add GPS points wrangled from data downloaded from iNaturalist project
          + Note ArcGIS Pro was doing a weird thing where after opening gps csv, it wouldn't recognize lat/long columns the next time I tried to add it as a layer.
            + Copy original GPS file as a new file specifically for use in ARCGIS
          + If you add csv as table with 'add data' button in Map Tab of ArcGIS Pro, you can then right click the layer and select 'display XY data'
            + It will add a layer with your points
          
### Subset Data        
     
  * Subset Data (needed to avoid insufficient memory error)
      + Add soils polygons for each state MUPOLYGON
        + Again, click 'add data' browse to .gdb and then find MUPolygon in list. 
        + Rename polygon for each state (e.g. WA MUPolygon)
      + Use select by location for Tree GPS points (find tool in Map Tab of ArcGIS Pro)
        + Input features - gps.csv
        + Relationship - Intersectselect 
        + Selecting Features - WA MUPOLYGON
        + Selection type - New Selection
      + Save selected
        + Right click point layer -> Selection -> Make layer from selected features
        + Rename layer (e.g. Washington GPS Points)
        
> Note ArcGIS Pro was doing something ackward where it would re-add the Washington points to the OR shapefile and vice versa. One workaround was to export it as a csv immediately after adding selection as new layer, then displaying the XY data as described above. 
      
### Join Data 

> Note there are many tables and datasets that may be more valuable for other analyses. Check the table [here](https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download/?cid=stelprdb1241115&ext=pdf) for a list of tables. Tip-search for keywords you're interested in. 
    
   * Join Data (Follow gSSUGO User Guide for joining Data) - complete for each state
      + Muaggatt data
        + right click raster -> select Joins and relates -> Add Join
          + Input: OR MapunitRaster_10m
          + Input Join Field: MUKEY
          + Join Table: OR Mapunit Aggregated Attribute (muaggatt)
            + Note you may need to browse to the folder containing the gSSURGO_OR.gbd geodatabase.
          + Join Table Field: MUKEY
      + Repeat with Valu1 table
      + Repeat with Component TAble
        + This time use Input Join Field 'MUPOLYGON.MUKEY or VAT_OR MApunitRaster_10m.MUKEY'
        + Might not have MUKEY file for join field, instead use 'Map Unit Key'
      + Repeat with Component Ecological Class (coecoclass) Table
        + Note this table is based of the above component key (relates), therefore component needs to be joined first. 
          + Use Component.cokey as join field
          + use Component Key (cokey) as input field. 
      + (Optional) Not recommended though -too much data - Repeat with Chorizon Table
        + Use Component.cokey and Component Key as Join Fields
      + (Optional) Note the same process can possibly be followed for adding table data to the shape file (MUPOLYGON).
        + Directions for using shapefiles are available here [YouTube Video](https://youtu.be/zGfT1v8Fmug)
          + This process also involves Dissolve to Dissolve Shapefile by MUKEY - split rows with same MUKEY values?

> Note the valu1 table has a seperate reference for the dataset. 

### Extract data for points     
     
  * Extract raster data for points
      + followed directions here https://support.esri.com/en/technical-article/000022163
        + Note need to subset data to avoid 'ERROR 010005: unable to allocate memory'
        + Extract Values to Points (Search to find tool) - you will need License for Spatial Analyst Tools)
        + Input Point Feature - Washington GPS Points
        + Input Raster - WA MapunitRaster_10m 2
        + Output Point Features - extract_GPS_Washington
          + Check 'Interpolate values at the point locations' (note, I am not sure if this is the best choice)
            + In theory, this models values for points based on surrounding data, it may fill some of the gaps?
            + Note, unchecking this option did *not* speed up the extraction process. 
          + Check 'Append all the input raster attributes to the output point features'
            + note, raster data is not included if we do not check this option 
  

> Note the column headers were not extracted correctly following this protocol! 

Apparently, .shp files can only have fields 10 characters long, so it was automatically truncating the field names. The [help](https://pro.arcgis.com/en/pro-app/latest/tool-reference/spatial-analyst/extract-values-to-points.htm) suggests extracting it as a geodatabase rather than a shapefile in this case: 

"The shapefile format has a limitation on the maximum length of a field name of 10 characters. As a result, any fields that are appended to the attribute table of an output shapefile will have their names truncated and made unique by default. This may make it difficult to distinguish between the fields, particularly if the names are long or very similar. In this case, it is suggested to output to a file geodatabase instead."

**Solution: do not extract new file into different folder than the geodatabase for the project you're working in.** If you just name the extract file and do not designate where it is saved, it should keep all of the fieldnames, then you can export it to CSV with fieldnames. It should work if you are saving the export inside the project geodatabase. 

          
### Export Data to table
        
  * Export GPS data with soils data as .csv
        + Right click layer created above (Extract_GPS_Washington) -> Data -> Export Table
          + Input rows - Extract_GPS_Washington 
          + browse to folder to save file (e.g. redcedar/serverfiles/data)
          + be sure to add '.csv' to end of file name (e.g. Washington_GPS_Soils_Data.csv)
      
### Visualize Shape Files

  * (Optional) Visualize raster data
      + Change symbology of raster files
        + right click layer and select symbology
          + select classify then change field to bedrock depth or other variable of interest.
    


    