---
title: "Soil Data Extraction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The purpose of this Markdown Document is to record the methods for extracting soils data for the redcedar GPS points.

Unforuntately, I had to do this with windows because the soils data I am first exploring are provided in arcmap database formats (.gdb). 

* Possible options to move forward include: 
  + Maybe I could actually convert them in ArcMap to another format? 
  + Extracting data from rasters(?) for gps points and exporting into csv format for analyses in OSX using ArcMap.
  + Look for alternative soils data that are in another format
  
Below are the methods I used to extract the soils data for the GPS points.

* Procedure:
  + Download gSSURGO data from the [USDA Geospatial Data Gateway](https://gdg.sc.egov.usda.gov/GDGHome_DirectDownLoad.aspx)
    + click on the link to 'Soils' - Redirects you to a the [NRCS Box Folder](https://nrcs.app.box.com/v/soils)
    + I downloaded OR and WA data from the folder 'October 2021 gSSURGO by State'.
    + Working with gSSURGO data is kind of ackward because you have to join tables of interest to the base raster file before you can map those table variables.
  + ArcMap procedure 
      + Add Data
          + Add MapunitRaster_10m for each state, rename content based on state
          + Add muaggatt attribute table for each state, rename content based on state
      + Join Data (Follow gSSUGO User Guide for joining Data) - complete for each state
          + Click on aggregated attribute table, select data ribbon, click joins.
            + Input: OR MapunitRaster_10m
            + Input Join Field: MUKEY
            + Join Table: OR Mapunit Aggregated Attribute
            + Join Table Field: MUKEY
      + Change symbology of raster files
          + right click layer and select symbology
            + select classify then change field to bedrock depth or other variable of interest.
      + Extract raster data for points
          + followed directions here https://support.esri.com/en/technical-article/000022163
          
    
    
    
    