---
title: "Topo Data Extraction - ArcGIS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

The purpose of this Markdown Document is to record the methods for extracting topo data for the 1500 redcedar GPS points using ArcGIS.

## ArcGIS Toolbox

Topo data were extracted for each point using the Geomorphometry and Gradient Metrics Toolbox available [here](https://www.arcgis.com/home/item.html?id=63ffcecf3b2a45bf99a84cdaedefaccf). 

The toolbox was developed by Jeffrey Evans. More information is available at: 
https://evansmurphy.wixsite.com/evansspatial/arcgis-gradient-metrics-toolbox

Evans JS, Oakleaf J, Cushman SA (2014) An ArcGIS Toolbox for Surface Gradient and Geomorphometric Modeling, version 2.0-0. URL: https://github.com/jeffreyevans/GradientMetrics Accessed: `r format(Sys.time(), '%d %B, %Y')`.

A manuscript about the package is available [here](https://www.sciencedirect.com/science/article/pii/S0098300415300613). 

## Explanitory variables

This package extracts neat data for gps points that can be useful as explanitory variables for the response of tree health. For example, this dataset includes calculations for heat load index and transformations for aspect. 

* Variables
  + CTI - similar to TWI
  + Slope Position
  + Heat Load Index - slope, aspect and latitude
  + second derivited slope - concave vs convexity? 
  + Transformed Aspect - may be included in heat load index
  


## Data

The data used in the below models are described in the [Data Wrangle folder](./data-wrangle). 

Download DEMs


https://earthexplorer.usgs.gov/

* Earth Explorer (https://earthexplorer.usgs.gov/)
  + Search Criteria
    + Circle, selected seattle as center point
    + 600 km radius
  + Data sets
    + Digital Elevation
      + GTOP030
  + Results
    + Downloaded two DEMS
      + Entity ID: GT30W140N40
      + Entity ID: GT30W140N90


Note these rasters may be too large or have too poor of resolution for use with the geomorphometric toolbox. 
We kept getting errors while trying to create HLI rasters, so we decided to try a DEMs with higher resolution and smaller areas. 
      
      
* National Map (https://apps.nationalmap.gov/downloader/#/)
  + Define Area of Interest
    + Selectable Polygon
      + US State or Territory
        + Washington (repeat below with Oregon)
  + Search Products
    + Elevational Products (3DEP)
      + 1/3 arc-second DEM
        + Current
        + 1x1 degree
        + GeoTiff
  + Add all relevant products to cart (repeat with Oregon)
  + Download Data
    + follow instructions for batch download using uGet
    + Note each tile is about 500MBs


## Methods

* Process
  + Add iNat observations
    + Map tab -> Add Data -> Browse to below folder
    + C:\Users\pnwbi\ServerFiles\redcedar\data
          + Add CSV with iNat GPS - Add GPS points wrangled from data downloaded from iNaturalist project
          + Note ArcGIS Pro was doing a weird thing where after opening gps csv, it wouldn't recognize lat/long columns the next time I tried to add it as a layer.
            + Copy original GPS file as a new file specifically for use in ARCGIS
          + If you add csv as table with 'add data' button in Map Tab of ArcGIS Pro, you can then right click the layer and select 'display XY data'
            + It will add a layer with your points
  + Use DEMS to generate HLIs for each tile
  + Merge HLI Rasters
  + Extract HLI data for points in rasters
  

